// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import AstroPWA from '@vite-pwa/astro';

const BASE = '/ToscaBase';

/** Sidebar: four mastery levels, each holding autogenerated topic groups (see CONTENT_GUIDE.md). */
const topic = (label, ru, directory) => ({ label, translations: { ru }, items: [{ autogenerate: { directory } }] });
const sidebar = [
	{
		label: '1 · Foundations',
		translations: { ru: '1 · Основы' },
		items: [
			topic('Getting started', 'Начало работы', 'getting-started'),
			topic('Modules', 'Модули', 'modules'),
			topic('Test cases', 'Тест-кейсы', 'test-cases'),
		],
	},
	{
		label: '2 · Building tests',
		translations: { ru: '2 · Построение тестов' },
		collapsed: true,
		items: [
			topic('Test case design', 'Дизайн тест-кейсов', 'test-case-design'),
			topic('Standard modules', 'Стандартные модули', 'standard-modules'),
			topic('Expressions', 'Выражения', 'expressions'),
			topic('Data and parameters', 'Данные и параметры', 'data-and-parameters'),
			topic('Execution', 'Выполнение', 'execution'),
		],
	},
	{
		label: '3 · Specialised',
		translations: { ru: '3 · Специализация' },
		collapsed: true,
		items: [
			topic('Engines', 'Движки', 'engines'),
			topic('API testing', 'Тестирование API', 'api-testing'),
			topic('Requirements and reporting', 'Требования и отчёты', 'requirements-and-reporting'),
			topic('Best practices', 'Лучшие практики', 'best-practices'),
			topic('Troubleshooting', 'Решение проблем', 'troubleshooting'),
		],
	},
	{
		label: '4 · Enterprise',
		translations: { ru: '4 · Enterprise' },
		collapsed: true,
		items: [topic('Administration', 'Администрирование', 'administration')],
	},
	topic('Reference', 'Справочник', 'reference'),
];

// https://astro.build/config
export default defineConfig({
	site: 'https://letulip.github.io',
	base: BASE,
	integrations: [
		starlight({
			title: 'ToscaBase',
			defaultLocale: 'root',
			locales: {
				root: { label: 'English', lang: 'en' },
				ru: { label: 'Русский', lang: 'ru' },
			},
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/letulip/ToscaBase' }],
			sidebar,
			customCss: ['./src/styles/custom.css'],
			components: {
				// Appends the per-page "Sources" list (see the `sources` frontmatter field).
				MarkdownContent: './src/components/MarkdownContent.astro',
			},
			head: [
				// PWA: web app manifest + service worker registration (registerSW.js is emitted by @vite-pwa/astro).
				{ tag: 'link', attrs: { rel: 'manifest', href: `${BASE}/manifest.webmanifest` } },
				{ tag: 'script', attrs: { src: `${BASE}/registerSW.js`, defer: true } },
				{ tag: 'meta', attrs: { name: 'theme-color', content: '#7c3aed' } },
				{ tag: 'link', attrs: { rel: 'apple-touch-icon', href: `${BASE}/icons/icon-192.png` } },
			],
		}),
		AstroPWA({
			registerType: 'autoUpdate',
			base: `${BASE}/`,
			scope: `${BASE}/`,
			includeAssets: ['favicon.svg', 'icon.svg'],
			manifest: {
				name: 'ToscaBase',
				short_name: 'ToscaBase',
				description: 'Tricentis Tosca knowledge base. Reworked from video tutorials, searchable offline.',
				lang: 'en',
				theme_color: '#7c3aed',
				background_color: '#18141f',
				display: 'standalone',
				start_url: `${BASE}/`,
				scope: `${BASE}/`,
				icons: [
					{ src: `${BASE}/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
					{ src: `${BASE}/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
					{ src: `${BASE}/icons/icon-maskable-192.png`, sizes: '192x192', type: 'image/png', purpose: 'maskable' },
					{ src: `${BASE}/icons/icon-maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
				],
			},
			workbox: {
				globPatterns: [
					'**/*.{html,css,js,json,svg,png,woff2,wasm,webmanifest}',
					'**/*.{pf_meta,pf_fragment,pf_index}',
					'pagefind/*.js',
					// Pagefind ships its wasm as pagefind/wasm.<lang>.pagefind
					'pagefind/*.{wasm,pagefind}',
				],
				maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
				// The experimental transform rewrites the `404.html` precache entry to `404`,
				// so the fallback must reference that URL or createHandlerBoundToURL() throws.
				navigateFallback: `${BASE}/404`,
				navigateFallbackDenylist: [/\/pagefind\//],
			},
			experimental: {
				directoryAndTrailingSlashHandler: true,
			},
		}),
	],
});
