// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import AstroPWA from '@vite-pwa/astro';

const BASE = '/ToscaBase';

/** One autogenerated sidebar group per top-level docs directory. */
const sidebar = [
	{ label: 'Getting started', translations: { ru: 'Начало работы' }, items: [{ autogenerate: { directory: 'getting-started' } }] },
	{ label: 'Modules', translations: { ru: 'Модули' }, items: [{ autogenerate: { directory: 'modules' } }] },
	{ label: 'Test cases', translations: { ru: 'Тест-кейсы' }, items: [{ autogenerate: { directory: 'test-cases' } }] },
	{ label: 'Test case design', translations: { ru: 'Дизайн тест-кейсов' }, items: [{ autogenerate: { directory: 'test-case-design' } }] },
	{ label: 'Standard modules', translations: { ru: 'Стандартные модули' }, items: [{ autogenerate: { directory: 'standard-modules' } }] },
	{ label: 'Engines', translations: { ru: 'Движки' }, items: [{ autogenerate: { directory: 'engines' } }] },
	{ label: 'Expressions', translations: { ru: 'Выражения' }, items: [{ autogenerate: { directory: 'expressions' } }] },
	{ label: 'Execution', translations: { ru: 'Выполнение' }, items: [{ autogenerate: { directory: 'execution' } }] },
	{ label: 'Data and parameters', translations: { ru: 'Данные и параметры' }, items: [{ autogenerate: { directory: 'data-and-parameters' } }] },
	{ label: 'API testing', translations: { ru: 'Тестирование API' }, items: [{ autogenerate: { directory: 'api-testing' } }] },
	{ label: 'Requirements and reporting', translations: { ru: 'Требования и отчёты' }, items: [{ autogenerate: { directory: 'requirements-and-reporting' } }] },
	{ label: 'Administration', translations: { ru: 'Администрирование' }, items: [{ autogenerate: { directory: 'administration' } }] },
	{ label: 'Best practices', translations: { ru: 'Лучшие практики' }, items: [{ autogenerate: { directory: 'best-practices' } }] },
	{ label: 'Troubleshooting', translations: { ru: 'Решение проблем' }, items: [{ autogenerate: { directory: 'troubleshooting' } }] },
	{ label: 'Reference', translations: { ru: 'Справочник' }, items: [{ autogenerate: { directory: 'reference' } }] },
];

// https://astro.build/config
export default defineConfig({
	site: 'https://letulip.github.io',
	base: BASE,
	integrations: [
		starlight({
			title: 'ToscaBase',
			defaultLocale: 'root',
			locales: {
				root: { label: 'English', lang: 'en' },
				ru: { label: 'Русский', lang: 'ru' },
			},
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/letulip/ToscaBase' }],
			sidebar,
			customCss: ['./src/styles/custom.css'],
			components: {
				// Appends the per-page "Sources" list (see the `sources` frontmatter field).
				MarkdownContent: './src/components/MarkdownContent.astro',
			},
			head: [
				// PWA: web app manifest + service worker registration (registerSW.js is emitted by @vite-pwa/astro).
				{ tag: 'link', attrs: { rel: 'manifest', href: `${BASE}/manifest.webmanifest` } },
				{ tag: 'script', attrs: { src: `${BASE}/registerSW.js`, defer: true } },
				{ tag: 'meta', attrs: { name: 'theme-color', content: '#7c3aed' } },
				{ tag: 'link', attrs: { rel: 'apple-touch-icon', href: `${BASE}/icons/icon-192.png` } },
			],
		}),
		AstroPWA({
			registerType: 'autoUpdate',
			base: `${BASE}/`,
			scope: `${BASE}/`,
			includeAssets: ['favicon.svg', 'icon.svg'],
			manifest: {
				name: 'ToscaBase',
				short_name: 'ToscaBase',
				description: 'Tricentis Tosca knowledge base. Reworked from video tutorials, searchable offline.',
				lang: 'en',
				theme_color: '#7c3aed',
				background_color: '#18141f',
				display: 'standalone',
				start_url: `${BASE}/`,
				scope: `${BASE}/`,
				icons: [
					{ src: `${BASE}/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
					{ src: `${BASE}/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
					{ src: `${BASE}/icons/icon-maskable-192.png`, sizes: '192x192', type: 'image/png', purpose: 'maskable' },
					{ src: `${BASE}/icons/icon-maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
				],
			},
			workbox: {
				globPatterns: [
					'**/*.{html,css,js,json,svg,png,woff2,wasm,webmanifest}',
					'**/*.{pf_meta,pf_fragment,pf_index}',
					'pagefind/*.js',
					// Pagefind ships its wasm as pagefind/wasm.<lang>.pagefind
					'pagefind/*.{wasm,pagefind}',
				],
				maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
				// The experimental transform rewrites the `404.html` precache entry to `404`,
				// so the fallback must reference that URL or createHandlerBoundToURL() throws.
				navigateFallback: `${BASE}/404`,
				navigateFallbackDenylist: [/\/pagefind\//],
			},
			experimental: {
				directoryAndTrailingSlashHandler: true,
			},
		}),
	],
});
